Insert into Estado (Id, CodigoUf, Nome, Uf, Regiao) values ('1', '12', 'Acre', 'AC', 'Norte');
Insert into Estado (Id, CodigoUf, Nome, Uf, Regiao) values ('2', '27', 'Alagoas', 'AL', 'Nordeste');
Insert into Estado (Id, CodigoUf, Nome, Uf, Regiao) values ('3', '16', 'Amapá', 'AP', 'Norte');
Insert into Estado (Id, CodigoUf, Nome, Uf, Regiao) values ('4', '13', 'Amazonas', 'AM', 'Norte');
Insert into Estado (Id, CodigoUf, Nome, Uf, Regiao) values ('5', '29', 'Bahia', 'BA', 'Nordeste');
Insert into Estado (Id, CodigoUf, Nome, Uf, Regiao) values ('6', '23', 'Ceará', 'CE', 'Nordeste');
Insert into Estado (Id, CodigoUf, Nome, Uf, Regiao) values ('7', '53', 'Distrito Federal', 'DF', 'Centro-Oeste');
Insert into Estado (Id, CodigoUf, Nome, Uf, Regiao) values ('8', '32', 'Espírito Santo', 'ES', 'Sudeste');
Insert into Estado (Id, CodigoUf, Nome, Uf, Regiao) values ('9', '52', 'Goiás', 'GO', 'Centro-Oeste');
Insert into Estado (Id, CodigoUf, Nome, Uf, Regiao) values ('10', '21', 'Maranhão', 'MA', 'Nordeste');
Insert into Estado (Id, CodigoUf, Nome, Uf, Regiao) values ('11', '51', 'Mato Grosso', 'MT', 'Centro-Oeste');
Insert into Estado (Id, CodigoUf, Nome, Uf, Regiao) values ('12', '50', 'Mato Grosso do Sul', 'MS', 'Centro-Oeste');
Insert into Estado (Id, CodigoUf, Nome, Uf, Regiao) values ('13', '31', 'Minas Gerais', 'MG', 'Sudeste');
Insert into Estado (Id, CodigoUf, Nome, Uf, Regiao) values ('14', '15', 'Pará', 'PA', 'Nordeste');
Insert into Estado (Id, CodigoUf, Nome, Uf, Regiao) values ('15', '25', 'Paraíba', 'PB', 'Nordeste');
Insert into Estado (Id, CodigoUf, Nome, Uf, Regiao) values ('16', '41', 'Paraná', 'PR', 'Sul');
Insert into Estado (Id, CodigoUf, Nome, Uf, Regiao) values ('17', '26', 'Pernambuco', 'PE', 'Nordeste');
Insert into Estado (Id, CodigoUf, Nome, Uf, Regiao) values ('18', '22', 'Piauí', 'PI', 'Nordeste');
Insert into Estado (Id, CodigoUf, Nome, Uf, Regiao) values ('19', '33', 'Rio de Janeiro', 'RJ', 'Sudeste');
Insert into Estado (Id, CodigoUf, Nome, Uf, Regiao) values ('20', '24', 'Rio Grande do Norte', 'RN', 'Nordeste');
Insert into Estado (Id, CodigoUf, Nome, Uf, Regiao) values ('21', '43', 'Rio Grande do Sul', 'RS', 'Sul');
Insert into Estado (Id, CodigoUf, Nome, Uf, Regiao) values ('22', '11', 'Rondônia', 'RO', 'Norte');
Insert into Estado (Id, CodigoUf, Nome, Uf, Regiao) values ('23', '14', 'Roraima', 'RR', 'Norte');
Insert into Estado (Id, CodigoUf, Nome, Uf, Regiao) values ('24', '42', 'Santa Catarina', 'SC', 'Sul');
Insert into Estado (Id, CodigoUf, Nome, Uf, Regiao) values ('25', '35', 'São Paulo', 'SP', 'Sudeste');
Insert into Estado (Id, CodigoUf, Nome, Uf, Regiao) values ('26', '28', 'Sergipe', 'SE', 'Nordeste');
Insert into Estado (Id, CodigoUf, Nome, Uf, Regiao) values ('27', '17', 'Tocantins', 'TO', 'Norte');
