Insert into ESTADO (ID,NOME,UF) values ('1','Acre','AC');
Insert into ESTADO (ID,NOME,UF) values ('2','Alagoas','AL');
Insert into ESTADO (ID,NOME,UF) values ('3','Amazonas','AM');
Insert into ESTADO (ID,NOME,UF) values ('4','Amapá','AP');
Insert into ESTADO (ID,NOME,UF) values ('5','Bahia','BA');
Insert into ESTADO (ID,NOME,UF) values ('6','Ceará','CE');
Insert into ESTADO (ID,NOME,UF) values ('7','Distrito Federal','DF');
Insert into ESTADO (ID,NOME,UF) values ('8','Espírito Santo','ES');
Insert into ESTADO (ID,NOME,UF) values ('9','Goiás','GO');
Insert into ESTADO (ID,NOME,UF) values ('10','Maranhão','MA');
Insert into ESTADO (ID,NOME,UF) values ('11','Minas Gerais','MG');
Insert into ESTADO (ID,NOME,UF) values ('12','Mato Grosso do Sul','MS');
Insert into ESTADO (ID,NOME,UF) values ('13','Mato Grosso','MT');
Insert into ESTADO (ID,NOME,UF) values ('14','Pará','PA');
Insert into ESTADO (ID,NOME,UF) values ('15','Paraíba','PB');
Insert into ESTADO (ID,NOME,UF) values ('16','Pernambuco','PE');
Insert into ESTADO (ID,NOME,UF) values ('17','Piauí','PI');
Insert into ESTADO (ID,NOME,UF) values ('18','Paraná','PR');
Insert into ESTADO (ID,NOME,UF) values ('19','Rio de Janeiro','RJ');
Insert into ESTADO (ID,NOME,UF) values ('20','Rio Grande do Norte','RN');
Insert into ESTADO (ID,NOME,UF) values ('21','Rondônia','RO');
Insert into ESTADO (ID,NOME,UF) values ('22','Roraima','RR');
Insert into ESTADO (ID,NOME,UF) values ('23','Rio Grande do Sul','RS');
Insert into ESTADO (ID,NOME,UF) values ('24','Santa Catarina','SC');
Insert into ESTADO (ID,NOME,UF) values ('25','Sergipe','SE');
Insert into ESTADO (ID,NOME,UF) values ('26','São Paulo','SP');
Insert into ESTADO (ID,NOME,UF) values ('27','Tocantins','TO');
