Insert into Estado (Id, CodigoUf, Nome, Uf) values ('1', '12', 'Acre', 'AC');
Insert into Estado (Id, CodigoUf, Nome, Uf) values ('2', '27', 'Alagoas', 'AL');
Insert into Estado (Id, CodigoUf, Nome, Uf) values ('3', '16', 'Amapá', 'AP');
Insert into Estado (Id, CodigoUf, Nome, Uf) values ('4', '13', 'Amazonas', 'AM');
Insert into Estado (Id, CodigoUf, Nome, Uf) values ('5', '29', 'Bahia', 'BA');
Insert into Estado (Id, CodigoUf, Nome, Uf) values ('6', '23', 'Ceará', 'CE');
Insert into Estado (Id, CodigoUf, Nome, Uf) values ('7', '53', 'Distrito Federal', 'DF');
Insert into Estado (Id, CodigoUf, Nome, Uf) values ('8', '32', 'Espírito Santo', 'ES');
Insert into Estado (Id, CodigoUf, Nome, Uf) values ('9', '52', 'Goiás', 'GO');
Insert into Estado (Id, CodigoUf, Nome, Uf) values ('10', '21', 'Maranhão', 'MA');
Insert into Estado (Id, CodigoUf, Nome, Uf) values ('11', '51', 'Mato Grosso', 'MT');
Insert into Estado (Id, CodigoUf, Nome, Uf) values ('12', '50', 'Mato Grosso do Sul', 'MS');
Insert into Estado (Id, CodigoUf, Nome, Uf) values ('13', '31', 'Minas Gerais', 'MG');
Insert into Estado (Id, CodigoUf, Nome, Uf) values ('14', '15', 'Pará', 'PA');
Insert into Estado (Id, CodigoUf, Nome, Uf) values ('15', '25', 'Paraíba', 'PB');
Insert into Estado (Id, CodigoUf, Nome, Uf) values ('16', '41', 'Paraná', 'PR');
Insert into Estado (Id, CodigoUf, Nome, Uf) values ('17', '26', 'Pernambuco', 'PE');
Insert into Estado (Id, CodigoUf, Nome, Uf) values ('18', '22', 'Piauí', 'PI');
Insert into Estado (Id, CodigoUf, Nome, Uf) values ('19', '33', 'Rio de Janeiro', 'RJ');
Insert into Estado (Id, CodigoUf, Nome, Uf) values ('20', '24', 'Rio Grande do Norte', 'RN');
Insert into Estado (Id, CodigoUf, Nome, Uf) values ('21', '43', 'Rio Grande do Sul', 'RS');
Insert into Estado (Id, CodigoUf, Nome, Uf) values ('22', '11', 'Rondônia', 'RO');
Insert into Estado (Id, CodigoUf, Nome, Uf) values ('23', '14', 'Roraima', 'RR');
Insert into Estado (Id, CodigoUf, Nome, Uf) values ('24', '42', 'Santa Catarina', 'SC');
Insert into Estado (Id, CodigoUf, Nome, Uf) values ('25', '35', 'São Paulo', 'SP');
Insert into Estado (Id, CodigoUf, Nome, Uf) values ('26', '28', 'Sergipe', 'SE');
Insert into Estado (Id, CodigoUf, Nome, Uf) values ('27', '17', 'Tocantins', 'TO');
